# Generated by Django 6.0.4 on 2026-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Target IP")),
                ("hostname", models.CharField(blank=True, max_length=200, null=True)),
                ("open_ports", models.CharField(blank=True, max_length=200)),
                (
                    "vulnerability_status",
                    models.CharField(
                        choices=[
                            ("Clean", "Clean"),
                            ("Vulnerable", "Vulnerable"),
                            ("Exploited", "Exploited"),
                        ],
                        default="Clean",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
